# Generated by Django 2.2.10 on 2020-02-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='课程内容'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='视频链接'),
        ),
    ]
